### ISSUE TITLE
Dependencies not compatible with Node LTS

### ISSUE THREAD

**Issue by nazimjamil** [sonatype-nexus-community/auditjs#20] opened 2017-07-04 14:08 UTC
When installing with `yarn` it appears that an auditjs dependency is not compatible with Node 6.11.0
```
error extract-text-webpack-plugin@2.1.2: The engine "node" is incompatible with this module. Expected version ">=4.3.0 < 5.0.0 || >= 5.10".
error Found incompatible module
```
The error can be circumvented with `--ignore-engines`, however, it may be a better idea to test with the latest long term support version and update.

**Comment by OSSIndex-Admin** [comment] 2017-07-04 16:42
Thanks for the report. I will see what I can do.

**Comment by OSSIndex-Admin** [comment] 2017-07-12 04:57
Hi. FYI, I have been away and trying to find a new house lately so have not had a chance to work on this (moving 1600km/1000miles). I have not forgotten, and will finally be stationary again starting this weekend. I will hopefully have a better solution for you soon.

**Comment by nazimjamil** [comment] 2017-07-12 06:48
Not to worry, I'll have a look too and see if there's anything I can contribute to.

**Comment by OSSIndex-Admin** [comment] 2017-07-22 14:38
Hi. I finally have a test system up and running, but cannot reproduce the issue. I wonder if one of the downstream modules have been updated. Here are my specifics:

OS: Ubuntu 16.04.2 LTS
node: 6.11.1
npm: 3.10.10
yarn: 0.27.3

What versions are you running on? The command I am running is rather simple, and perhaps does not match your use case:

    yarn init
    yarn add auditjs

Should there be extra setup (perhaps in the packages.json file for my new module)?

**Comment by ajurgenson55** [comment] 2020-01-22 23:14
Closing this as we've rewritten the codebase, reopen if this is still an issue

**Closed by ajurgenson55** 2020-01-22 23:14 UTC
